//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
//This source code was auto-generated by MonoXSD
//
namespace Microsoft.Build.Schemas {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003", IsNullable=false)]
    public partial class Project {





        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", Order=0)]
        public PropertyGroupType[] PropertyGroup { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup", Order=1)]
        public ItemGroupType[] ItemGroup { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemDefinitionGroup", Order=2)]
        public ItemDefinitionGroupType[] ItemDefinitionGroup { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Choose", Order=3)]
        public ChooseType[] Choose { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsingTask", Order=4)]
        public UsingTaskType[] UsingTask { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectExtensions", Order=5)]
        public System.Xml.XmlNode[] ProjectExtensions { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TargetType Target { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ImportType Import { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ImportGroupType ImportGroup { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", Order=9)]
        public PropertyGroupType[] PropertyGroup1 { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup", Order=10)]
        public ItemGroupType[] ItemGroup1 { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemDefinitionGroup", Order=11)]
        public ItemDefinitionGroupType[] ItemDefinitionGroup1 { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Choose", Order=12)]
        public ChooseType[] Choose1 { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsingTask", Order=13)]
        public UsingTaskType[] UsingTask1 { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target", Order=14)]
        public TargetType[] Target1 { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import", Order=15)]
        public ImportType[] Import1 { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImportGroup", Order=16)]
        public ImportGroupType[] ImportGroup1 { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectExtensions", Order=17)]
        public System.Xml.XmlNode[] ProjectExtensions1 { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultTargets { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InitialTargets { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sdk { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToolsVersion { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class PropertyGroupType {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public object[] Property { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class GenericPropertyType {

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class UsingTaskBodyType {
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Evaluate { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class UsingTaskType {


        /// <remarks/>
        public System.Xml.XmlElement ParameterGroup { get; set; }
        /// <remarks/>
        public UsingTaskBodyType Task { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AssemblyName { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AssemblyFile { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TaskName { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TaskFactory { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Architecture { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Runtime { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class OtherwiseType {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Choose", typeof(ChooseType))]
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup", typeof(ItemGroupType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", typeof(PropertyGroupType))]
        public object[] Items { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ChooseType {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("When")]
        public WhenType[] When { get; set; }
        /// <remarks/>
        public OtherwiseType Otherwise { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class WhenType {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Choose", typeof(ChooseType))]
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup", typeof(ItemGroupType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", typeof(PropertyGroupType))]
        public object[] Items { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ItemGroupType {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", typeof(SimpleItemType))]
        [System.Xml.Serialization.XmlElementAttribute("Link", typeof(LinkItem))]
        [System.Xml.Serialization.XmlElementAttribute("PostBuildEvent", typeof(PostBuildEventItem))]
        [System.Xml.Serialization.XmlElementAttribute("PreBuildEvent", typeof(PreBuildEventItem))]
        [System.Xml.Serialization.XmlElementAttribute("ResourceCompile", typeof(ResourceCompile))]
        public SimpleItemType[] Items { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostBuildEventItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PreBuildEventItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceCompile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinkItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericItemType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute("Item", Namespace="http://schemas.microsoft.com/developer/msbuild/2003", IsNullable=false)]
    public partial class SimpleItemType {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Exclude { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remove { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Update { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class PostBuildEventItem : SimpleItemType {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Command", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("Message", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType3[] ItemsElementName { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003", IncludeInSchema=false)]
    public enum ItemsChoiceType3 {
        /// <remarks/>
        Command,

        /// <remarks/>
        Message,
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class PreBuildEventItem : SimpleItemType {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Command", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("Message", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        /// <remarks/>
        Command,

        /// <remarks/>
        Message,
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ResourceCompile : SimpleItemType {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalIncludeDirectories", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("Culture", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("IgnoreStandardIncludePath", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("NullTerminateStrings", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("PreprocessorDefinitions", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ResourceOutputFileName", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ShowProgress", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("SuppressStartupBanner", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("UndefinePreprocessorDefinitions", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        /// <remarks/>
        AdditionalIncludeDirectories,
        /// <remarks/>
        Culture,
        /// <remarks/>
        IgnoreStandardIncludePath,
        /// <remarks/>
        NullTerminateStrings,
        /// <remarks/>
        PreprocessorDefinitions,
        /// <remarks/>
        ResourceOutputFileName,
        /// <remarks/>
        ShowProgress,
        /// <remarks/>
        SuppressStartupBanner,
        /// <remarks/>
        UndefinePreprocessorDefinitions,
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class LinkItem : SimpleItemType {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddModuleNamesToAssembly", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("AdditionalDependencies", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("AdditionalLibraryDirectories", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("AdditionalManifestDependencies", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("AllowIsolation", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("AssemblyDebug", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("AssemblyLinkResource", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("BaseAddress", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("CLRImageType", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("CLRSupportLastError", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("CLRThreadAttribute", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("CLRUnmanagedCodeCheck", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("CreateHotPatchableImage", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("DataExecutionPrevention", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("DelayLoadDLLs", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("DelaySign", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("Driver", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("EmbedManagedResourceFile", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("EnableCOMDATFolding", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("EnableUAC", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("EntryPointSymbol", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("FixedBaseAddress", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ForceFileOutput", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ForceSymbolReferences", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("FunctionOrder", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("GenerateDebugInformation", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("GenerateMapFile", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("HeapCommitSize", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("HeapReserveSize", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("IgnoreAllDefaultLibraries", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("IgnoreEmbeddedIDL", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("IgnoreSpecificDefaultLibraries", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("IgnoreStandardIncludePath", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ImageHasSafeExceptionHandlers", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ImportLibrary", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("KeyContainer", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("KeyFile", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("LargeAddressAware", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("LinkErrorReporting", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("LinkStatus", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("LinkTimeCodeGeneration", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MSDOSStubFileName", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MapExports", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MapFileName", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MergeSections", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MergedIDLBaseFileName", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MidlCommandFile", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("MinimumRequiredVersion", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ModuleDefinitionFile", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("OptimizeReferences", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("OutputFile", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("PreventDllBinding", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("Profile", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ProfileGuidedDatabase", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ProgramDatabaseFile", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("RandomizedBaseAddress", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("RegisterOutput", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("SectionAlignment", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("ShowProgress", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("SpecifySectionAttributes", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("StackCommitSize", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("StackReserveSize", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("StripPrivateSymbols", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("SubSystem", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("SupportNobindOfDelayLoadedDLL", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("SupportUnloadOfDelayLoadedDLL", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("SuppressStartupBanner", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("SwapRunFromCD", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("SwapRunFromNET", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("TargetMachine", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("TerminalServerAware", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("TreatLinkerWarningAsErrors", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("TypeLibraryFile", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("TypeLibraryResourceID", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("UACExecutionLevel", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("UACUIAccess", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("Version", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        /// <remarks/>
        AddModuleNamesToAssembly,
        /// <remarks/>
        AdditionalDependencies,
        /// <remarks/>
        AdditionalLibraryDirectories,
        /// <remarks/>
        AdditionalManifestDependencies,
        /// <remarks/>
        AllowIsolation,
        /// <remarks/>
        AssemblyDebug,
        /// <remarks/>
        AssemblyLinkResource,
        /// <remarks/>
        BaseAddress,
        /// <remarks/>
        CLRImageType,
        /// <remarks/>
        CLRSupportLastError,
        /// <remarks/>
        CLRThreadAttribute,
        /// <remarks/>
        CLRUnmanagedCodeCheck,
        /// <remarks/>
        CreateHotPatchableImage,
        /// <remarks/>
        DataExecutionPrevention,
        /// <remarks/>
        DelayLoadDLLs,
        /// <remarks/>
        DelaySign,
        /// <remarks/>
        Driver,
        /// <remarks/>
        EmbedManagedResourceFile,
        /// <remarks/>
        EnableCOMDATFolding,
        /// <remarks/>
        EnableUAC,
        /// <remarks/>
        EntryPointSymbol,
        /// <remarks/>
        FixedBaseAddress,
        /// <remarks/>
        ForceFileOutput,
        /// <remarks/>
        ForceSymbolReferences,
        /// <remarks/>
        FunctionOrder,
        /// <remarks/>
        GenerateDebugInformation,
        /// <remarks/>
        GenerateMapFile,
        /// <remarks/>
        HeapCommitSize,
        /// <remarks/>
        HeapReserveSize,
        /// <remarks/>
        IgnoreAllDefaultLibraries,
        /// <remarks/>
        IgnoreEmbeddedIDL,
        /// <remarks/>
        IgnoreSpecificDefaultLibraries,
        /// <remarks/>
        IgnoreStandardIncludePath,
        /// <remarks/>
        ImageHasSafeExceptionHandlers,
        /// <remarks/>
        ImportLibrary,
        /// <remarks/>
        KeyContainer,
        /// <remarks/>
        KeyFile,
        /// <remarks/>
        LargeAddressAware,
        /// <remarks/>
        LinkErrorReporting,
        /// <remarks/>
        LinkStatus,
        /// <remarks/>
        LinkTimeCodeGeneration,
        /// <remarks/>
        MSDOSStubFileName,
        /// <remarks/>
        MapExports,
        /// <remarks/>
        MapFileName,
        /// <remarks/>
        MergeSections,
        /// <remarks/>
        MergedIDLBaseFileName,
        /// <remarks/>
        MidlCommandFile,
        /// <remarks/>
        MinimumRequiredVersion,
        /// <remarks/>
        ModuleDefinitionFile,
        /// <remarks/>
        OptimizeReferences,
        /// <remarks/>
        OutputFile,
        /// <remarks/>
        PreventDllBinding,
        /// <remarks/>
        Profile,
        /// <remarks/>
        ProfileGuidedDatabase,
        /// <remarks/>
        ProgramDatabaseFile,
        /// <remarks/>
        RandomizedBaseAddress,
        /// <remarks/>
        RegisterOutput,
        /// <remarks/>
        SectionAlignment,
        /// <remarks/>
        ShowProgress,
        /// <remarks/>
        SpecifySectionAttributes,
        /// <remarks/>
        StackCommitSize,
        /// <remarks/>
        StackReserveSize,
        /// <remarks/>
        StripPrivateSymbols,
        /// <remarks/>
        SubSystem,
        /// <remarks/>
        SupportNobindOfDelayLoadedDLL,
        /// <remarks/>
        SupportUnloadOfDelayLoadedDLL,
        /// <remarks/>
        SuppressStartupBanner,
        /// <remarks/>
        SwapRunFromCD,
        /// <remarks/>
        SwapRunFromNET,
        /// <remarks/>
        TargetMachine,
        /// <remarks/>
        TerminalServerAware,
        /// <remarks/>
        TreatLinkerWarningAsErrors,
        /// <remarks/>
        TypeLibraryFile,
        /// <remarks/>
        TypeLibraryResourceID,
        /// <remarks/>
        UACExecutionLevel,
        /// <remarks/>
        UACUIAccess,
        /// <remarks/>
        Version,
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class GenericItemType : SimpleItemType {
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ItemDefinitionGroupType {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", typeof(SimpleItemType))]
        [System.Xml.Serialization.XmlElementAttribute("Link", typeof(LinkItem))]
        [System.Xml.Serialization.XmlElementAttribute("PostBuildEvent", typeof(PostBuildEventItem))]
        [System.Xml.Serialization.XmlElementAttribute("PreBuildEvent", typeof(PreBuildEventItem))]
        [System.Xml.Serialization.XmlElementAttribute("ResourceCompile", typeof(ResourceCompile))]
        public SimpleItemType[] Items { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ImportType {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Project { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sdk { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MinimumVersion { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ImportGroupType {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import")]
        public ImportType[] Import { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class OnErrorType {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExecuteTargets { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class TargetType {



        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup", typeof(ItemGroupType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", typeof(PropertyGroupType))]
        [System.Xml.Serialization.XmlElementAttribute("Task", typeof(TaskType))]
        public object[] Items { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OnError")]
        public OnErrorType[] OnError { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DependsOnTargets { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inputs { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Outputs { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KeepDuplicateOutputs { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Returns { get; set; }
        /// <remarks/>
        /// [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BeforeTargets { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AfterTargets { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute("Task", Namespace="http://schemas.microsoft.com/developer/msbuild/2003", IsNullable=false)]
    public partial class TaskType {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Output")]
        public TaskTypeOutput[] Output { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContinueOnError { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Architecture { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Runtime { get; set; }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class TaskTypeOutput {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TaskParameter { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PropertyName { get; set; }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition { get; set; }
    }
}
